# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-18 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripBuddy_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('travel_date_start', models.DateField(auto_now_add=True)),
                ('travel_date_to', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updtaed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
