# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-19 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TripBuddy_app', '0002_traveltrip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traveltrip',
            old_name='travel_date_start',
            new_name='travel_date_from',
        ),
        migrations.RemoveField(
            model_name='traveltrip',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='traveltrip',
            name='updtaed_at',
        ),
    ]
