# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-19 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TripBuddy_app', '0003_auto_20180819_1201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TravelTrip',
        ),
    ]
