# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-20 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TripBuddy_app', '0005_traveltrip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TravelTrip',
        ),
    ]
