# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-21 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TripBuddy_app', '0007_traveltrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddtoTravelGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TripBuddy_app.TravelTrip')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TripBuddy_app.User')),
            ],
        ),
    ]
