# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-21 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TripBuddy_app', '0010_traveltrip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveltrip',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='TravelTrip',
        ),
    ]
